//! Pass case: `#[derive(AccountGroupFields)]` on a struct with a single
//! `AccountRefMut` field. Verifies `DERIVED_FIELD_COUNT == 1` and that
//! `DERIVED_FIELD_METADATA` has one entry for the field.

use bytemuck::{Pod, Zeroable};
use solana_address::Address;
use solzempic::{AccountGroupField, Loadable};

// Define a minimal Framework (normally generated by #[SolzempicEntrypoint]
// or `solzempic::define_framework!`).
pub struct TestFramework;
impl solzempic::Framework for TestFramework {
    const PROGRAM_ID: Address = Address::new_from_array([0u8; 32]);
}

pub type AccountRefMut<'a, T> = solzempic::AccountRefMut<'a, T, TestFramework>;

// A minimal Pod account type for use with AccountRefMut.
#[repr(C)]
#[derive(Clone, Copy, Pod, Zeroable)]
pub struct Counter {
    pub discriminator: [u8; 8],
    pub count: u64,
}

impl Loadable for Counter {
    const DISCRIMINATOR: u8 = 1;
    const LEN: usize = core::mem::size_of::<Self>();
}

#[derive(solzempic::AccountGroupFields)]
pub struct SimpleCtx<'a> {
    pub counter: AccountRefMut<'a, Counter>,
}

fn main() {
    // Verify derive produced the expected constants.
    assert_eq!(SimpleCtx::DERIVED_FIELD_COUNT, 1);
    let meta: &'static [AccountGroupField] = SimpleCtx::DERIVED_FIELD_METADATA;
    assert_eq!(meta.len(), 1);
    assert_eq!(meta[0].name, "counter");
    assert!(meta[0].is_writable);
    assert!(!meta[0].is_signer);
    assert!(!meta[0].is_program);
}
