[package]
name = "solzempic-integration-tests"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
solzempic-test-program = { path = "../test-program", features = ["no-entrypoint"] }
litesvm = "0.6"
solana-sdk = "2.2"
solana-program = "2.2"
solana-address = { version = "2.0", features = ["bytemuck"] }
bytemuck = { version = "1.14", features = ["derive", "min_const_generics"] }
