[package]
name = "solzempic-integration-tests"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
solzempic-test-program = { path = "../test-program", features = ["no-entrypoint"] }
litesvm = "0.9"
solana-sdk = "3"
solana-program = "3"
solana-system-interface = { version = "3", features = ["bincode"] }
solana-address = { version = "2.0", features = ["bytemuck"] }
bytemuck = { version = "1.14", features = ["derive", "min_const_generics"] }
